import type { Metadata } from "next";
import type { ReactNode } from "react";

export const metadata: Metadata = { title: "Privacy Policy", description: "How PrediQs AI collects, uses, and protects your information." };

function Section({ title, children }: { title: string; children: ReactNode }) {
  return <section className="border-t border-edge py-7 first:border-0 first:pt-0"><h2 className="mb-3 font-display text-xl font-semibold text-ice">{title}</h2><div className="space-y-3 leading-7 text-muted [&_a]:text-volt [&_li]:ml-5 [&_li]:list-disc [&_strong]:font-semibold [&_strong]:text-ice">{children}</div></section>;
}

export default function PrivacyPage() {
  return <main className="min-h-screen bg-night px-5 py-14 sm:px-8 sm:py-20"><article className="mx-auto max-w-3xl rounded-2xl border border-edge bg-panel p-6 sm:p-10 lg:p-12">
    <p className="font-mono text-xs font-semibold uppercase tracking-[0.2em] text-volt">Legal</p><h1 className="mt-3 font-display text-4xl font-bold text-ice sm:text-5xl">Privacy Policy</h1><p className="mb-10 mt-3 text-sm text-muted">Last updated: July 21, 2026</p>
    <Section title="1. Introduction"><p>Welcome to PrediQs AI (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;). We are committed to protecting your personal information and your right to privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our mobile application and website (collectively, the &quot;Service&quot;).</p><p><strong>Please note: PrediQs AI is a sports information, analytics, and tracking tool. We do not operate a sportsbook, and our Service does not accept real-money wagers, facilitate gambling transactions, or distribute prize money. All bankroll tracking is for personal informational purposes only.</strong></p><p>Please read this policy carefully. If you do not agree with its terms, please discontinue use of our Service.</p></Section>
    <Section title="2. Information We Collect"><p>We collect information that you provide directly to us, including:</p><ul><li><strong>Account information:</strong> Email address, username, and password when you register.</li><li><strong>Profile data:</strong> Bankroll settings, betting preferences, and notification preferences.</li><li><strong>Transaction data:</strong> Bankroll entries, bet records, and financial tracking data you input.</li><li><strong>Communications:</strong> Messages you send to our AI assistant or support team.</li><li><strong>Device information:</strong> Device type, operating system, app version, crash data, and, when applicable, mobile advertising identifiers.</li><li><strong>Usage data:</strong> Features used, pages viewed, time spent, and interaction data.</li><li><strong>Device permissions:</strong> With your explicit consent, access to push notifications or other native features. You can revoke access in device settings.</li></ul></Section>
    <Section title="3. How We Use Your Information"><p>We use the information we collect to:</p><ul><li>Provide, operate, and improve our Service</li><li>Personalize your experience and deliver AI-powered predictions</li><li>Process payments and manage your subscription</li><li>Send transactional and promotional communications (with your consent)</li><li>Monitor and analyse usage patterns to improve features</li><li>Detect and prevent fraud, abuse, and security incidents</li><li>Comply with legal obligations</li></ul></Section>
    <Section title="4. AI & Data Processing"><p>Our AI features use the Anthropic Claude API to generate sports predictions and chat responses. When you interact with our AI assistant, your messages are processed by Anthropic&apos;s API. We do not share personally identifiable information beyond what is necessary to provide the service. Conversation data may be retained to improve our AI models.</p></Section>
    <Section title="5. Data Sharing"><p>We do not sell your personal information. We may share your information with:</p><ul><li><strong>Service providers:</strong> Third-party vendors who help us deliver our Service (e.g., payment processors, hosting).</li><li><strong>Analytics and Crash Reporting:</strong> Third-party services (such as Google Analytics or Firebase) to collect crash reports and usage metrics to improve app stability.</li><li><strong>AI providers:</strong> Anthropic for AI chat and prediction features.</li><li><strong>Legal authorities:</strong> When required by law, court order, or government regulation.</li><li><strong>Business transfers:</strong> In connection with a merger, acquisition, or sale of assets.</li></ul></Section>
    <Section title="6. Data Retention & Account Deletion"><p>We retain personal information while your account is active or as needed to provide services. Some data may be retained for legal compliance for up to 7 years.</p><p><strong>Account and Data Deletion:</strong> You may initiate deletion in account settings or submit a verifiable request to <a href="mailto:support@prediqsai.com">support@prediqsai.com</a>. We will erase your profile, bankroll data, and chat history except where retention is strictly required by law.</p></Section>
    <Section title="7. Security"><p>We implement industry-standard measures including encryption in transit (TLS), bcrypt password hashing, JWT authentication, and secure storage on your device. However, no internet transmission method is 100% secure.</p></Section>
    <Section title="8. Children's Privacy"><p>Our Service is not directed to individuals under the age of 18. We do not knowingly collect personal information from minors. If we become aware that a child under 18 has provided us with personal information, we will take steps to delete such information.</p></Section>
    <Section title="9. Your Rights"><p>Depending on your location, you may have the right to:</p><ul><li>Access and receive a copy of your personal data</li><li>Correct inaccurate or incomplete data</li><li>Request deletion of your personal data</li><li>Object to or restrict processing of your data</li><li>Data portability (receive your data in a machine-readable format)</li><li>Withdraw consent at any time</li></ul><p>To exercise these rights, contact us at <a href="mailto:support@prediqsai.com">support@prediqsai.com</a>.</p></Section>
    <Section title="10. Changes to This Policy"><p>We may update this policy. We will identify changes through the &quot;Last updated&quot; date and notify you in the app or by email when changes are significant.</p></Section>
    <Section title="11. Contact Us"><div className="rounded-xl border border-edge bg-night p-5"><p><strong>PrediQs AI</strong></p><p>Email: <a href="mailto:support@prediqsai.com">support@prediqsai.com</a></p><p>Website: <a href="https://prediqsai.com">prediqsai.com</a></p></div></Section>
  </article></main>;
}
