import type { Metadata } from "next";
import type { ReactNode } from "react";

export const metadata: Metadata = { title: "Terms of Service", description: "Terms governing use of PrediQs AI." };
function Section({ title, children }: { title: string; children: ReactNode }) {
  return <section className="border-t border-edge py-7 first:border-0 first:pt-0"><h2 className="mb-3 font-display text-xl font-semibold text-ice">{title}</h2><div className="space-y-3 leading-7 text-muted [&_a]:text-volt [&_li]:ml-5 [&_li]:list-disc [&_strong]:font-semibold [&_strong]:text-ice">{children}</div></section>;
}

export default function TermsPage() {
  return <main className="min-h-screen bg-night px-5 py-14 sm:px-8 sm:py-20"><article className="mx-auto max-w-3xl rounded-2xl border border-edge bg-panel p-6 sm:p-10 lg:p-12">
    <p className="font-mono text-xs font-semibold uppercase tracking-[0.2em] text-volt">Legal</p><h1 className="mt-3 font-display text-4xl font-bold text-ice sm:text-5xl">Terms of Service</h1><p className="mb-10 mt-3 text-sm text-muted">Last updated: May 22, 2026</p>
    <Section title="1. Acceptance of Terms"><p>By downloading, installing, or using the PrediQs AI mobile application or website (collectively, the &quot;Service&quot;), you agree to be bound by these Terms. If you do not agree, do not use the Service.</p><p>You must be at least <strong>18 years of age</strong>. You represent that you are 18 or older and your jurisdiction permits access to sports betting-related information.</p></Section>
    <Section title="2. Description of Service"><p>PrediQs AI provides AI-powered sports analytics, predictions, odds comparison, and bankroll management tools for informational and entertainment purposes. We use the Anthropic Claude AI model and publicly available sports data.</p><p><strong>IMPORTANT DISCLAIMER: PrediQs AI is NOT a gambling operator, bookmaker, or betting exchange. We do not accept wagers or process gambling transactions. Predictions do not constitute gambling advice or guarantees.</strong></p><p><strong>Platform Independence:</strong> Google LLC, Google Play, and Apple Inc. are not sponsors of, nor involved with, the Service, predictions, bankroll tracking, or promotional activities.</p></Section>
    <Section title="3. User Accounts"><p>When you create an account, you agree to:</p><ul><li>Provide accurate and complete registration information</li><li>Maintain the security of your password and account</li><li>Notify us immediately of any unauthorised use of your account</li><li>Take responsibility for all activities under your account</li><li>Not share your account credentials with others</li></ul><p><strong>Account Deletion:</strong> You have the right to terminate your account at any time. To request the complete deletion of your account and all associated personal data from our systems, please contact our support team at <a href="mailto:support@prediqsai.com">support@prediqsai.com</a>.</p></Section>
    <Section title="4. Subscription and Payments"><p>PrediQs AI offers the following subscription tiers:</p><ul><li><strong>Free:</strong> Limited access with 5 AI predictions per day at no cost.</li><li><strong>Premium Monthly:</strong> $29.99/month, full access to all features.</li><li><strong>Premium Annual:</strong> $319/year (billed annually), full access to all features.</li><li><strong>Lifetime:</strong> $299 one-time payment, permanent full access.</li></ul><p>Subscriptions auto-renew unless cancelled at least 24 hours before the renewal date. You may cancel at any time through your device&apos;s subscription management settings. Refunds are subject to the applicable app store&apos;s refund policy.</p></Section>
    <Section title="5. Responsible Gambling"><div className="rounded-xl border border-gold/30 bg-gold/5 p-5"><p className="font-semibold text-gold">Responsible Gambling Warning</p><p>Gambling can be addictive and cause financial and personal harm. Never bet more than you can afford to lose. If you may have a gambling problem, seek help immediately.</p><p><strong>National Problem Gambling Helpline:</strong> <a href="tel:18005224700">1-800-522-4700</a> (24/7) · <a href="https://www.ncpgambling.org">ncpgambling.org</a></p></div></Section>
    <Section title="6. Intellectual Property"><p>The Service and its original content, features, and functionality are owned by PrediQs AI and protected by intellectual property laws. You may not reproduce, distribute, modify, display, or exploit content without written permission.</p></Section>
    <Section title="7. Prohibited Uses"><p>You agree not to:</p><ul><li>Use the Service in any jurisdiction where sports betting analysis is prohibited by law</li><li>Reverse-engineer, decompile, or disassemble any part of the Service</li><li>Use automated tools to scrape, crawl, or extract data from the Service</li><li>Resell or redistribute AI predictions or proprietary data to third parties</li><li>Attempt to gain unauthorised access to our systems or networks</li><li>Use the Service for any illegal or unauthorised purpose</li><li>Harass, abuse, or harm other users</li></ul></Section>
    <Section title="8. Disclaimer of Warranties"><p>THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND. TO THE FULLEST EXTENT PERMITTED BY LAW, WE DISCLAIM ALL IMPLIED WARRANTIES.</p><p>WE DO NOT WARRANT THAT AI PREDICTIONS ARE ACCURATE, RELIABLE, OR PROFITABLE. SPORTS OUTCOMES ARE UNCERTAIN AND PAST PERFORMANCE DOES NOT INDICATE FUTURE RESULTS.</p></Section>
    <Section title="9. Limitation of Liability"><p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, PREDIQSAI SHALL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOST PROFITS, FUNDS WAGERED, OR OTHER LOSSES ARISING FROM USE OF THE SERVICE.</p></Section>
    <Section title="10. Governing Law"><p>These Terms are governed by applicable law. Disputes arising under them are subject to binding arbitration.</p></Section>
    <Section title="11. Changes to Terms"><p>We may modify these Terms and will identify material changes through the updated date and notice in the Service. Continued use constitutes acceptance.</p></Section>
    <Section title="12. Contact"><p>For questions, contact <a href="mailto:support@prediqsai.com">support@prediqsai.com</a>.</p></Section>
  </article></main>;
}
