"use client";

import Link from "next/link";
import { FormEvent, useEffect, useRef, useState } from "react";
import { ArrowLeft, Eye, ImageUp, Save, Send, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { ApiError, apiFetch } from "@/lib/api";
import { useAuth } from "@/lib/auth";
import { BlogMeta, EMPTY_BLOG_META, extractBlogMeta, withBlogMeta } from "@/lib/blogMeta";
import { BlogPost, apiErrorMessage } from "./types";

const AUTO_SAVE_PREFIX = "prediqs_sync_article_";
const MAX_BYTES = 3 * 1024 * 1024;
const allowed = ["image/jpeg", "image/png", "image/webp"];
function slugify(value: string) { return value.normalize("NFKD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, ""); }

export default function PostEditor({ postId }: { postId?: number }) {
  const { user, token } = useAuth(); const router = useRouter(); const editor = useRef<HTMLTextAreaElement>(null);
  const storageKey = `${AUTO_SAVE_PREFIX}${postId ?? "new"}`;
  const [title, setTitle] = useState(""); const [slug, setSlug] = useState(""); const [slugTouched, setSlugTouched] = useState(false); const [excerpt, setExcerpt] = useState(""); const [content, setContent] = useState(""); const [author, setAuthor] = useState(""); const [meta, setMeta] = useState<BlogMeta>(EMPTY_BLOG_META); const [saving, setSaving] = useState<"draft" | "publish" | null>(null); const [uploading, setUploading] = useState(false); const [error, setError] = useState(""); const [preview, setPreview] = useState(false); const [autosaved, setAutosaved] = useState(false);
  useEffect(() => { if (!postId && user && !author) setAuthor(user.displayName || user.username || "PrediQs AI"); }, [postId, user, author]);
  useEffect(() => { if (!postId || !token) return; apiFetch<{ posts: BlogPost[] }>("/admin/blog", { token }).then(({ posts }) => { const post = posts.find((item) => item.id === postId); if (!post) throw new Error("Article not found."); const decoded = extractBlogMeta(post.content); setTitle(post.title); setSlug(post.slug); setSlugTouched(true); setExcerpt(post.excerpt || ""); setContent(decoded.content); setMeta(decoded.meta); setAuthor(post.author || "PrediQs AI"); }).catch((e) => setError(apiErrorMessage(e, "Unable to load article."))); }, [postId, token]);
  useEffect(() => { const draft = localStorage.getItem(storageKey); if (!postId && draft) { try { const saved = JSON.parse(draft) as { title: string; slug: string; excerpt: string; content: string; author: string; meta: BlogMeta }; setTitle(saved.title); setSlug(saved.slug); setExcerpt(saved.excerpt); setContent(saved.content); setAuthor(saved.author); setMeta(saved.meta); setSlugTouched(Boolean(saved.slug)); } catch { localStorage.removeItem(storageKey); } } }, [postId, storageKey]);
  useEffect(() => { const interval = window.setInterval(() => { if (title || content) { localStorage.setItem(storageKey, JSON.stringify({ title, slug, excerpt, content, author, meta })); setAutosaved(true); } }, 30000); return () => window.clearInterval(interval); }, [title, slug, excerpt, content, author, meta, storageKey]);
  const updateMeta = (key: keyof BlogMeta, value: string) => setMeta((old) => ({ ...old, [key]: value }));
  function insert(value: string) { const field = editor.current; if (!field) return; const start = field.selectionStart; setContent(`${content.slice(0, start)}${value}${content.slice(field.selectionEnd)}`); requestAnimationFrame(() => field.focus()); }
  async function upload(file?: File) {
    if (!file) return; setError("");
    if (!allowed.includes(file.type)) { setError("Image upload rejected: use JPG, PNG, or WebP."); return; }
    if (file.size > MAX_BYTES) { setError("Image upload rejected: images must be 3MB or smaller."); return; }
    if (!token) { setError("Image upload failed (401): your session has expired. Please sign in again."); return; }
    setUploading(true);
    try { const form = new FormData(); form.set("file", file); const response = await fetch("/api/blog-images", { method: "POST", headers: { Authorization: `Bearer ${token}` }, body: form }); const body = await response.json().catch(() => ({})) as { url?: string; error?: string }; if (!response.ok || !body.url) throw new ApiError(response.status, body.error || "Upload failed."); updateMeta("featuredImage", body.url); }
    catch (e) { setError(e instanceof ApiError ? `Image upload failed (${e.status}): ${e.message}` : apiErrorMessage(e, "Image upload failed.")); }
    finally { setUploading(false); }
  }
  async function save(publish: boolean) {
    setError(""); if (!title.trim() || !slug.trim() || !content.trim() || !author.trim() || !token) { setError("Cannot save: title, slug, content, author, and an active session are required."); return; }
    setSaving(publish ? "publish" : "draft");
    try { await apiFetch(postId ? `/admin/blog/${postId}` : "/admin/blog", { method: postId ? "PUT" : "POST", token, body: JSON.stringify({ title: title.trim(), slug: slug.trim(), excerpt: excerpt.trim() || (postId ? null : undefined), content: withBlogMeta(content, meta), author: author.trim(), publish }) }); localStorage.removeItem(storageKey); router.push("/sync/articles"); }
    catch (e) { setError(e instanceof ApiError ? `Unable to ${postId ? "update" : "create"} article (${e.status}): ${e.message}` : apiErrorMessage(e, "Unable to save article.")); setSaving(null); }
  }
  return <main className="mx-auto max-w-[1440px] px-5 py-8 lg:px-8"><div className="flex flex-col gap-4 border-b border-white/8 pb-6 lg:flex-row lg:items-center lg:justify-between"><div><Link href="/sync/articles" className="inline-flex items-center gap-2 text-sm text-muted hover:text-volt"><ArrowLeft className="h-4 w-4" /> Articles</Link><h1 className="mt-3 font-display text-3xl font-bold">{postId ? "Edit article" : "New article"}</h1>{autosaved && <p className="mt-1 text-xs text-muted">Recovery copy saved locally.</p>}</div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => setPreview(true)} className="inline-flex items-center gap-2 rounded-lg border border-edge px-4 py-3 text-sm font-semibold hover:border-volt/50"><Eye className="h-4 w-4" /> Preview</button><button type="button" disabled={saving !== null} onClick={() => void save(false)} className="inline-flex items-center gap-2 rounded-lg border border-edge px-4 py-3 text-sm font-semibold text-ice hover:bg-panel"><Save className="h-4 w-4" /> {saving === "draft" ? "Saving..." : "Save as draft"}</button><button type="button" disabled={saving !== null} onClick={() => void save(true)} className="inline-flex items-center gap-2 rounded-lg bg-volt px-4 py-3 text-sm font-bold text-night"><Send className="h-4 w-4" /> {saving === "publish" ? "Publishing..." : "Publish now"}</button></div></div>
    {error && <p role="alert" className="mt-5 rounded-lg border border-danger/30 bg-danger/10 px-4 py-3 text-sm text-danger">{error}</p>}
    <form onSubmit={(e: FormEvent) => { e.preventDefault(); void save(false); }} className="mt-7 grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]"><section className="space-y-5"><label className="block text-sm font-medium">Article title<input value={title} onChange={(e) => { setTitle(e.target.value); if (!slugTouched) setSlug(slugify(e.target.value)); }} className="mt-2 w-full rounded-xl border border-white/10 bg-panel px-4 py-4 font-display text-xl outline-none focus:border-volt/60" /></label><div className="flex rounded-lg border border-white/8 bg-panel px-3 py-2"><span className="font-mono text-xs text-muted">prediqsai.com/blog/</span><input value={slug} onChange={(e) => { setSlugTouched(true); setSlug(slugify(e.target.value)); }} className="min-w-0 flex-1 bg-transparent font-mono text-sm text-volt outline-none" /></div><label className="block text-sm font-medium">Excerpt<textarea value={excerpt} onChange={(e) => setExcerpt(e.target.value)} rows={3} className="mt-2 w-full rounded-xl border border-white/10 bg-panel px-4 py-3 outline-none focus:border-volt/60" /></label><div className="overflow-hidden rounded-xl border border-white/10 bg-panel"><div className="flex gap-1 border-b border-white/8 p-2">{[["B", "**bold**"], ["H2", "\n## Heading\n"], ["Link", "[label](https://)"]].map(([label, value]) => <button key={label} type="button" onClick={() => insert(value)} className="rounded px-2 py-1 text-xs text-muted hover:bg-panel-2 hover:text-volt">{label}</button>)}</div><textarea ref={editor} value={content} onChange={(e) => setContent(e.target.value)} rows={22} placeholder="Start writing in Markdown..." className="w-full bg-transparent p-5 font-mono text-sm leading-7 outline-none" /></div></section>
      <aside className="space-y-5"><section className="rounded-xl border border-white/10 bg-panel p-5"><p className="font-display font-semibold">Author & category</p><label className="mt-4 block text-sm font-medium">Author<input value={author} onChange={(e) => setAuthor(e.target.value)} className="mt-2 w-full rounded-lg border border-white/10 bg-panel-2 px-3 py-2.5 outline-none" /></label><label className="mt-4 block text-sm font-medium">Category<input value={meta.category} onChange={(e) => updateMeta("category", e.target.value)} placeholder="Analysis, Strategy..." className="mt-2 w-full rounded-lg border border-white/10 bg-panel-2 px-3 py-2.5 outline-none" /></label></section><section className="rounded-xl border border-white/10 bg-panel p-5"><p className="font-display font-semibold">Featured image</p><label onDragOver={(e) => e.preventDefault()} onDrop={(e) => { e.preventDefault(); void upload(e.dataTransfer.files[0]); }} className="mt-4 flex cursor-pointer flex-col items-center rounded-lg border border-dashed border-edge px-4 py-7 text-center hover:border-volt/60"><ImageUp className="h-6 w-6 text-volt" /><span className="mt-3 text-sm font-medium">{uploading ? "Uploading..." : "Drop an image or choose a file"}</span><span className="mt-1 text-xs text-muted">JPG, PNG, WebP · max 3MB</span><input type="file" accept=".jpg,.jpeg,.png,.webp,image/jpeg,image/png,image/webp" onChange={(e) => void upload(e.target.files?.[0])} className="sr-only" /></label>{meta.featuredImage && <div className="mt-4"><img src={meta.featuredImage} alt="" className="aspect-video w-full rounded-lg object-cover" /><button type="button" onClick={() => updateMeta("featuredImage", "")} className="mt-2 inline-flex items-center gap-1 text-xs text-danger"><X className="h-3 w-3" /> Remove image</button></div>}</section><section className="rounded-xl border border-white/10 bg-panel p-5"><p className="font-display font-semibold">SEO & sharing</p><label className="mt-4 block text-sm font-medium">Custom meta title<input value={meta.metaTitle} onChange={(e) => updateMeta("metaTitle", e.target.value)} maxLength={70} className="mt-2 w-full rounded-lg border border-white/10 bg-panel-2 px-3 py-2.5 text-sm outline-none" /></label><label className="mt-4 block text-sm font-medium">Meta description<textarea value={meta.metaDescription} onChange={(e) => updateMeta("metaDescription", e.target.value)} maxLength={160} rows={3} className="mt-2 w-full rounded-lg border border-white/10 bg-panel-2 px-3 py-2.5 text-sm outline-none" /></label><label className="mt-4 block text-sm font-medium">Open Graph image URL<input type="url" value={meta.ogImage} onChange={(e) => updateMeta("ogImage", e.target.value)} className="mt-2 w-full rounded-lg border border-white/10 bg-panel-2 px-3 py-2.5 text-sm outline-none" /></label></section></aside></form>
    {preview && <div role="dialog" aria-modal="true" className="fixed inset-0 z-[100] overflow-y-auto bg-night/90 p-4 backdrop-blur"><div className="mx-auto my-8 max-w-3xl rounded-2xl border border-edge bg-night shadow-2xl"><div className="flex items-center justify-between border-b border-edge px-5 py-4"><span className="font-semibold">Article preview</span><button type="button" onClick={() => setPreview(false)} className="rounded-lg p-2 text-muted hover:bg-panel"><X className="h-4 w-4" /></button></div><article className="px-6 py-10 sm:px-12"><p className="font-mono text-xs uppercase tracking-[.2em] text-volt">{meta.category || "PrediQs research"}</p><h2 className="mt-4 font-display text-4xl font-bold">{title || "Untitled article"}</h2>{meta.featuredImage && <img src={meta.featuredImage} alt="" className="mt-8 aspect-[2/1] w-full rounded-xl object-cover" />}<p className="mt-5 text-lg text-muted">{excerpt}</p><div className="mt-8 whitespace-pre-line leading-8 text-muted">{content}</div></article></div></div>}
  </main>;
}